export const dashBoardElement = {
  PropertiesMenu: '[title="Properties"]',
  InventoriesMenu: '[data-menu-alias="inventories"]',
  PropertyNewForm: '[data-page="1"]',
  MultipleUnit: '[title="multiple-unit"]',
  Name: "#ProfileAddressName",
  LoadingOverlay: "#loading-overlay",
  PropertyOwnerDropdown: "#s2id_PropertyOwnerId",
  PropertyChoice: "#select2-drop li:nth-child(2)",
  Address1: ".sub-form #ProfileAddress1",
  Address2: ".sub-form #ProfileAddress2",
  City: ".sub-form #ProfileCity",
  PostalCode: ".sub-form #ProfilePostcode",
  Country: ".sub-form #ProfileCounty",
  Area: '.details-content-right [data-select-add-model="Area"]',
  FullyManage: ".checkbox #PropertyFullAccess",
  UnitCount: "#PropertyUnitCount",
  NextButton: "input.next-page.btn.btn-default",
  UnitRef: "#PrefixUnitProfileAddressName",
  unitType: '.unit-setting.let-component [data-select-add-model="UnitType"]',
  SelectManager: "#s2id_PrefixUnitUnitManagerManagerPersonId",
  SelectManagerDropDown: "#select2-drop .select2-result",
  CertType:
    "#s2id_RequiredCertificateMultiUnitUnitRequiredCertificateTypeIds .select2-search-field",
  CertTypeDropdown: "#select2-drop  li",
  UnitDetailType: '.edit-unit-detail [data-type="unit-type-id"]',
  UnitDetailOwner: '[data-type="owner-id"]',

  UnitDetailManager: '[data-type="manager-id"]',
  AddpropertyButton: '[value="Add Property"]',

  DashboardPropertyName: ".name .table-info",
};
